jobs:
  Job1:
    name: Job 1
    steps:
      - type: script
        script-content: |-
          ls 
          cat .teamcity.yml
  Job2:
    name: Job 2
    steps:
      - type: script
        script-content: cat README.md
    dependencies:
      - Job1
